In [88]:
#importing required libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn import metrics


In [89]:
#loading dataset

df = pd.read_csv("nifty_50_22-11-19--22-11-20.csv") 

In [90]:
#describing dataset

df.describe()

Open          High           Low         Close     Adj Close  \
count    250.000000    250.000000    250.000000    250.000000    250.000000   
mean   11021.071592  11098.325395  10917.198992  11006.848613  11006.848613   
std     1221.167407   1176.454912   1259.735893   1221.068538   1221.068538   
min     7735.149902   8036.950195   7511.100098   7610.250000   7610.250000   
25%    10110.974854  10201.449951  10037.824707  10122.650391  10122.650391   
50%    11361.449707  11410.100097  11279.875000  11319.924805  11319.924805   
75%    12027.787598  12078.050049  11943.212158  12012.350342  12012.350342   
max    12932.500000  12963.000000  12819.349609  12938.250000  12938.250000   

             Volume  
count  2.500000e+02  
mean   6.619900e+05  
std    2.109447e+05  
min    0.000000e+00  
25%    5.538000e+05  
50%    6.319500e+05  
75%    7.336250e+05  
max    1.811000e+06

In [91]:
df.shape

(250, 7)

In [92]:
df.head()

Date          Open          High           Low         Close  \
0  2019-11-22  11967.299805  11968.099609  11883.500000  11914.400391   
1  2019-11-25  11922.450195  12084.500000  11919.750000  12073.750000   
2  2019-11-26  12110.200195  12132.450195  12006.349609  12037.700195   
3  2019-11-27  12068.500000  12114.900391  12055.150391  12100.700195   
4  2019-11-28  12132.099609  12158.799805  12099.950195  12151.150391   

      Adj Close   Volume  
0  11914.400391   486800  
1  12073.750000   534300  
2  12037.700195  1201300  
3  12100.700195   584200  
4  12151.150391   620500

In [93]:
df = df.set_index("Date")

In [94]:
# split data 

y = df["Close"] 
X = df.drop(["Close", "Adj Close"], axis=1) 

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=.3)

In [95]:
# Taking care of missing data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X)
X = imputer.transform(X)

print(X)


[[1.19672998e+04 1.19680996e+04 1.18835000e+04 4.86800000e+05]
 [1.19224502e+04 1.20845000e+04 1.19197500e+04 5.34300000e+05]
 [1.21102002e+04 1.21324502e+04 1.20063496e+04 1.20130000e+06]
 [1.20685000e+04 1.21149004e+04 1.20551504e+04 5.84200000e+05]
 [1.21320996e+04 1.21587998e+04 1.20999502e+04 6.20500000e+05]
 [1.21462002e+04 1.21474004e+04 1.20174004e+04 8.04400000e+05]
 [1.21370498e+04 1.21371504e+04 1.20237002e+04 7.20900000e+05]
 [1.20676504e+04 1.20685996e+04 1.19564004e+04 6.05800000e+05]
 [1.19699502e+04 1.20547002e+04 1.19352998e+04 7.47200000e+05]
 [1.20712500e+04 1.20812002e+04 1.19987500e+04 5.62200000e+05]
 [1.20473496e+04 1.20570498e+04 1.18888496e+04 6.09200000e+05]
 [1.19390996e+04 1.19819502e+04 1.18880498e+04 5.99100000e+05]
 [1.19505000e+04 1.19532002e+04 1.18447002e+04 6.50200000e+05]
 [1.18673496e+04 1.19232002e+04 1.18322998e+04 9.97700000e+05]
 [1.19442998e+04 1.20055000e+04 1.19340000e+04 7.52600000e+05]
 [1.20264004e+04 1.20988496e+04 1.20235996e+04 5.977000

In [96]:
# Feature Scaling

sc = StandardScaler()
Xtrain = sc.fit_transform(Xtrain)
Xtest = sc.transform(Xtest)

In [97]:
print(Xtrain)

[[ 0.74116277  0.75601485  0.65384252 -0.16133356]
 [ 0.93596987  0.92412812  0.95580571 -1.98206971]
 [ 0.25714506  0.2171926   0.1389043  -0.03941944]
 [ 0.86099811  0.88291502  0.90441279 -0.9799812 ]
 [ 0.64268033  0.66272846  0.66578028 -0.2462177 ]
 [ 0.89518523  0.86837937  0.8849952  -1.01701119]
 [-1.19814669 -1.296489   -1.29087719  0.20213003]
 [ 1.11858078  1.09616444  0.99580439 -0.91389691]
 [ 0.65599485  0.68990032  0.67667112 -0.23311478]
 [-2.19701034 -1.83374169 -2.13483197  2.38974793]
 [ 0.8561593   0.82613389  0.82050179 -0.7253288 ]
 [ 0.53228128  0.51402401  0.48458678 -0.47637333]
 [ 0.25558549  0.20922227  0.11619228  0.8299308 ]
 [ 0.20540439  0.16693647  0.19281648 -0.87572753]
 [-1.28139502 -1.36470862 -1.34994448  0.41690398]
 [ 0.50341247  0.46298229  0.46854082 -0.24735708]
 [ 0.73472535  0.70195905  0.70728991 -0.01036514]
 [ 0.74064344  0.71959185  0.75693872 -0.85293985]
 [ 0.15454386  0.1005332   0.12061008 -0.36414397]
 [ 0.89274553  0.87568833  0.84

In [98]:
print(y)

Date
2019-11-22    11914.400391
2019-11-25    12073.750000
2019-11-26    12037.700195
2019-11-27    12100.700195
2019-11-28    12151.150391
                  ...     
2020-11-13    12719.950195
2020-11-17    12874.200195
2020-11-18    12938.250000
2020-11-19    12771.700195
2020-11-20    12859.049805
Name: Close, Length: 250, dtype: float64


In [99]:
# train model

reg= linear_model.LinearRegression()
reg.fit(Xtrain, ytrain) 

LinearRegression()

In [100]:
# prediction 

y_predicted = reg.predict(Xtest)

In [101]:
print(y_predicted)

[11912.08988493 12206.17547452  9284.36039455  9899.50793096
 11749.83890471 11822.9410939  10359.07422955 11598.53185297
  8977.16904118 11413.8343426  11804.54832223  9570.76006299
  9235.13127698 10029.19450309 11292.40562166 11123.5842619
 12067.51833362 10372.82067904 11843.81949233  9070.3885499
 12110.24105635 11734.3192327  10947.87510789 10536.19005218
 11279.75435626 11967.4295161  10813.06855274  9242.40950127
  9074.0327339  11387.56223717 12266.77387383 12678.91645773
  9012.06368253 11213.05687959 10324.63280712  9960.07165152
  9268.32155952  9232.23223428 10305.7090061   9583.77650721
 12382.16902915 11285.99191345  8432.61553145 10730.05202259
 11978.65567753  9538.36513612 11305.76417262 12073.93779273
 12212.96910422 12085.64204922 11357.46887335 12171.07664509
 11930.63026978 11430.89747748 11208.81474702  9947.10834532
 12820.03485246 11499.40391259 12231.66595924 12026.09173653
 11455.90355775 12168.74644896 11935.49597817 11884.13113254
 11183.00150101 11094.1813

In [102]:
print(ytest)

Date
2020-10-14    11971.049805
2020-01-09    12215.900391
2020-04-23     9313.900391
2020-06-01     9826.150391
2020-10-26    11767.750000
                  ...     
2020-04-08     8748.750000
2020-01-27    12119.000000
2020-09-01    11470.250000
2020-05-29     9580.299805
2020-06-09    10046.650391
Name: Close, Length: 75, dtype: float64


In [106]:

print("Test Accuracy (R^2 score):" + str((metrics.r2_score(ytest, reg.predict(Xtest)))*100))

Test Accuracy (R^2 score):99.57826728920861
